# Import Necessary Libraries

In [125]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px

# Load Data

In [126]:
df = pd.read_csv('vgsales.csv', index_col=0)
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Rank,,,,,,,,,,
1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

# Data Overview

### Check Data Info

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16598 entries, 1 to 16600
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16598 non-null  object
 1   Platform      16598 non-null  object
 2   Year          16327 non-null  float64
 3   Genre         16598 non-null  object
 4   Publisher     16540 non-null  object
 5   NA_Sales      16598 non-null  float64
 6   EU_Sales      16598 non-null  float64
 7   JP_Sales      16598 non-null  float64
 8   Other_Sales   16598 non-null  float64
 9   Global_Sales  16598 non-null  float64
dtypes: float64(6), object(4)
memory usage: 1.4+ MB

### Check summary statistics

In [128]:
df.describe().round(2)

           Year  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
count  16327.00  16598.00  16598.00  16598.00     16598.00      16598.00
mean    2006.41      0.26      0.15      0.08         0.05          0.54
std        5.83      0.82      0.51      0.31         0.19          1.56
min     1980.00      0.00      0.00      0.00         0.00          0.01
25%     2003.00      0.00      0.00      0.00         0.00          0.06
50%     2007.00      0.08      0.02      0.00         0.01          0.17
75%     2010.00      0.24      0.11      0.04         0.04          0.47
max     2020.00     41.49     29.02     10.22        10.57         82.74

In [129]:
df.describe(include= 'object')

                               Name Platform   Genre        Publisher
count                         16598    16598   16598            16540
unique                        11493       31      12              578
top     Need for Speed: Most Wanted       DS  Action  Electronic Arts
freq                             12     2163    3316             1351

### Check duplicates

In [130]:
df.duplicated().sum()

np.int64(1)

In [131]:
df.drop_duplicates(inplace= True, ignore_index= True)

In [132]:
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16592,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16593,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16594,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16595,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16596,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

### Check missing values

In [133]:
round((df.isna().mean()) * 100, 2)

Name            0.00
Platform        0.00
Year            1.63
Genre           0.00
Publisher       0.35
NA_Sales        0.00
EU_Sales        0.00
JP_Sales        0.00
Other_Sales     0.00
Global_Sales    0.00
dtype: float64

# Data Cleaning

In [134]:
# Make columns lowercase
df.columns = df.columns.str.lower()
df.columns

Index(['name', 'platform', 'year', 'genre', 'publisher', 'na_sales',
       'eu_sales', 'jp_sales', 'other_sales', 'global_sales'],
      dtype='object')

In [135]:
# Check count of dataframe if missing values were dropped from these collumns
df.dropna(subset= ['year'],inplace= True , ignore_index= True)

In [136]:
df.publisher = df.publisher.fillna('Unknown')

In [137]:
df

,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16322,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16323,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16324,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16325,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16326,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [138]:
round((df.isna().mean()) * 100, 3)

name            0.0
platform        0.0
year            0.0
genre           0.0
publisher       0.0
na_sales        0.0
eu_sales        0.0
jp_sales        0.0
other_sales     0.0
global_sales    0.0
dtype: float64

### Check Categorical Data in details

In [139]:
df.select_dtypes(include= 'object').columns

Index(['name', 'platform', 'genre', 'publisher'], dtype='object')

In [140]:
cat_cols = ['name', 'platform', 'genre', 'publisher']
cat_cols

['name', 'platform', 'genre', 'publisher']

In [141]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique(), '\n', '*' * 100)

name
11360
['Wii Sports' 'Super Mario Bros.' 'Mario Kart Wii' ... 'Plushees'
 'Woody Woodpecker in Crazy Castle 5' 'Know How 2']
 ****************************************************************************************************
platform
31
['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' '3DS' 'PS4' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'GC' 'WiiU' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']
 ****************************************************************************************************
genre
12
['Sports' 'Platform' 'Racing' 'Role-Playing' 'Puzzle' 'Misc' 'Shooter'
 'Simulation' 'Action' 'Fighting' 'Adventure' 'Strategy']
 ****************************************************************************************************
publisher
576
['Nintendo' 'Microsoft Game Studios' 'Take-Two Interactive'
 'Sony Computer Entertainment' 'Activision' 'Ubisoft' 'Bethesda Softworks'
 'Electronic Arts' 'Sega' 'SquareSoft' 'Atari' '505 Games' 'Capcom'
 'GT Interactive' 'Konami Digital Entertainment'
 'Sony Computer Entertainment Europe' 'Square Enix' 'LucasArts'
 'Virgin Interactive' 'Warner Bros. Interactive Entertainment'
 'Universal Interactive' 'Eidos Interactive' 'RedOctane' 'Vivendi Games'
 'Enix Corporation' 'Namco Bandai Games' 'Palcom' 'Hasbro Interactive'
 'THQ' 'Fox Interactive' 'Acclaim Entertainment' 'MTV Games'
 'Disney Interactive Studios' 'Majesco Entertainment' 'Codemasters'
 'Red Orb' 'Level 5' 'Arena Entertainment' 'Midway Games' 'JVC'
 'Deep Silver' '989 Studios' 'NCSoft' 'UEP Systems' 'Parker Bros.' 'Maxis'
 'Imagic' 'Tecmo Koei' 'Valve Software' 'ASCII Entertainment' 'Mindscape'
 'Infogrames' 'Unknown' 'Square' 'Valve' 'Activision Value' 'Banpresto'
 'D3Publisher' 'Oxygen Interactive' 'Red Storm Entertainment'
 'Video System' 'Hello Games' 'Global Star' 'Gotham Games'
 'Westwood Studios' 'GungHo' 'Crave Entertainment' 'Hudson Soft' 'Coleco'
 'Rising Star Games' 'Atlus' 'TDK Mediactive' 'ASC Games' 'Zoo Games'
 'Accolade' 'Sony Online Entertainment' '3DO' 'RTL' 'Natsume'
 'Focus Home Interactive' 'Alchemist' 'Black Label Games'
 'SouthPeak Games' 'Mastertronic' 'Ocean' 'Zoo Digital Publishing'
 'Psygnosis' 'City Interactive' 'Empire Interactive' 'Success' 'Compile'
 'Russel' 'Taito' 'Agetec' 'GSP' 'Microprose' 'Play It'
 'Slightly Mad Studios' 'Tomy Corporation' 'Sammy Corporation'
 'Koch Media' 'Game Factory' 'Titus' 'Marvelous Entertainment' 'Genki'
 'Mojang' 'Pinnacle' 'CTO SpA' 'TalonSoft' 'Crystal Dynamics' 'SCi'
 'Quelle' 'mixi, Inc' 'Rage Software' 'Ubisoft Annecy' 'Scholastic Inc.'
 'Interplay' 'Mystique' 'ChunSoft' 'Square EA'
 '20th Century Fox Video Games' 'Avanquest Software'
 'Hudson Entertainment' 'Nordic Games' 'Men-A-Vision' 'Nobilis'
 'Big Ben Interactive' 'Touchstone' 'Spike' 'Jester Interactive'
 'Nippon Ichi Software' 'LEGO Media' 'Quest' 'Illusion Softworks'
 'Tigervision' 'Funbox Media' 'Rocket Company' 'Metro 3D'
 'Mattel Interactive' 'IE Institute' 'Rondomedia'
 'Sony Computer Entertainment America' 'Universal Gamex' 'Ghostlight'
 'Wizard Video Games' 'BMG Interactive Entertainment' 'PQube'
 'Trion Worlds' 'Laguna' 'Ignition Entertainment' 'Takara'
 'Kadokawa Shoten' 'Destineer' 'Enterbrain' 'Xseed Games' 'Imagineer'
 'System 3 Arcade Software' 'CPG Products' 'Aruze Corp' 'Gamebridge'
 'Midas Interactive Entertainment' 'Jaleco' 'Answer Software' 'XS Games'
 'Activision Blizzard' 'Pack In Soft' 'Rebellion' 'Xplosiv'
 'GameMill Entertainment' 'Wanadoo' 'NovaLogic' 'Telltale Games' 'Epoch'
 'BAM! Entertainment' 'Knowledge Adventure' 'Mastiff' 'Tetris Online'
 'Harmonix Music Systems' 'ESP' 'TYO' 'Telegames' 'Mud Duck Productions'
 'Screenlife' 'Pioneer LDC' 'Magical Company' 'Mentor Interactive' 'Kemco'
 'Human Entertainment' 'Avanquest' 'Data Age' 'Electronic Arts Victor'
 'Black Bean Games' 'Jack of All Games' '989 Sports' 'Takara Tomy'
 'Media Rings' 'Elf' 'Starfish' 'Zushi Games' 'Jorudan'
 'Destination Software, Inc' 'New' 'Brash Entertainment'
 'ITT Family Games' 'PopCap Games' 'Home Entertainment Suppliers'
 'Ackkstudios' 'Starpath Corp.' 'P2 Games' 'BPS' 'Gathering of Developers'
 'NewKidCo' 'Storm City Games' 'CokeM Interactive' 'CBS Electronics'
 'Magix' 'Marvelous Interactive' 'Kalypso Media'
 'Nihon Falcom Corporation' 'Wargaming.net' 'Angel Studios'
 'Arc System Works' 'Playmates' 'SNK Playmore' 'Hamster Corporation'
 'From Software' 'Nippon Columbia' 'Nichibutsu' 'Little Orbit'
 'Conspiracy Entertainment' 'DTP Entertainment' 'Hect' 'Mumbo Jumbo'
 'Pacific Century Cyber Works' 'Indie Games' 'Liquid Games' 'NEC' 'Axela'
 'ArtDink' 'Sunsoft' 'Gust' 'SNK' 'NEC Interchannel' 'FuRyu'
 'Xing Entertainment' 'ValuSoft' 'Victor Interactive' 'Detn8 Games'
 'American Softworks' 'Nordcurrent' 'Bomb' 'Falcom Corporation'
 'AQ Interactive' 'CCP' 'Milestone S.r.l.' 'JoWood Productions'
 'Seta Corporation' 'On Demand' 'NCS' 'Aspyr' 'Gremlin Interactive Ltd'
 'Agatsuma Entertainment' 'Compile Heart' 'Culture Brain' 'Mad Catz'
 'Shogakukan' 'Merscom LLC' 'Rebellion Developments' 'Nippon Telenet'
 'TDK Core' 'bitComposer Games' 'Foreign Media Games' 'Astragon' 'SSI'
 'Kadokawa Games' 'Idea Factory' 'Performance Designed Products'
 'Asylum Entertainment' 'Core Design Ltd.' 'PlayV' 'UFO Interactive'
 'Idea Factory International' 'Playlogic Game Factory' 'Essential Games'
 'Adeline Software' 'Funcom' 'Panther Software' 'Blast! Entertainment Ltd'
 'Game Life' 'DSI Games' 'Avalon Interactive' 'Popcorn Arcade'
 'Neko Entertainment' 'Vir2L Studios' 'Aques' 'Syscom'
 'White Park Bay Software' 'System 3' 'Vatical Entertainment' 'Daedalic'
 'EA Games' 'Media Factory' 'Vic Tokai' 'The Adventure Company'
 'Game Arts' 'Broccoli' 'Acquire' 'General Entertainment'
 'Excalibur Publishing' 'Imadio' 'Swing! Entertainment'
 'Sony Music Entertainment' 'Aqua Plus' 'Paradox Interactive'
 'Hip Interactive' 'DreamCatcher Interactive' 'Tripwire Interactive'
 'Sting' 'Yacht Club Games' 'SCS Software' 'Bigben Interactive'
 'Havas Interactive' 'Slitherine Software' 'Graffiti' 'Funsta' 'Telstar'
 'U.S. Gold' 'DreamWorks Interactive' 'Data Design Interactive' 'MTO'
 'DHM Interactive' 'FunSoft' 'SPS' 'Bohemia Interactive'
 'Reef Entertainment' 'Tru Blu Entertainment' 'Moss' 'T&E Soft' 'O-Games'
 'Aksys Games' 'NDA Productions' 'Data East' 'Time Warner Interactive'
 'Gainax Network Systems' 'Daito' 'O3 Entertainment' 'Gameloft'
 'Xicat Interactive' 'Simon & Schuster Interactive' 'Valcon Games'
 'PopTop Software' 'TOHO' 'HMH Interactive' '5pb' 'Cave'
 'CDV Software Entertainment' 'Microids' 'PM Studios' 'Paon' 'Micro Cabin'
 'GameTek' 'Benesse' 'Type-Moon' 'Enjoy Gaming ltd.' 'Asmik Corp'
 'Interplay Productions' 'Asmik Ace Entertainment' 'inXile Entertainment'
 'Image Epoch' 'Phantom EFX' 'Evolved Games' 'responDESIGN'
 'Culture Publishers' 'Griffin International' 'Hackberry' 'Hearty Robin'
 'Nippon Amuse' 'Origin Systems' 'Seventh Chord' 'Mitsui' 'Milestone'
 'Abylight' 'Flight-Plan' 'Glams' 'Locus' 'Warp' 'Daedalic Entertainment'
 'Alternative Software' 'Myelin Media' 'Mercury Games'
 'Irem Software Engineering' 'Sunrise Interactive' 'Elite'
 'Evolution Games' 'Tivola' 'Global A Entertainment' 'Edia' 'Athena'
 'Aria' 'Gamecock' 'Tommo' 'Altron' 'Happinet' 'iWin' 'Media Works'
 'Fortyfive' 'Revolution Software' 'Imax' 'Crimson Cow' '10TACLE Studios'
 'Groove Games' 'Pack-In-Video' 'Insomniac Games'
 'Ascaron Entertainment GmbH' 'Asgard' 'Ecole' 'Yumedia' 'Phenomedia'
 'HAL Laboratory' 'Grand Prix Games' 'DigiCube' 'Creative Core'
 'Kaga Create' 'WayForward Technologies' 'LSP Games' 'ASCII Media Works'
 'Coconuts Japan' 'Arika' 'Ertain' 'Marvel Entertainment' 'Prototype'
 'Phantagram' '1C Company' 'The Learning Company' 'TechnoSoft' 'Vap'
 'Misawa' 'Tradewest' 'Team17 Software' 'Yeti' 'Pow' 'Navarre Corp'
 'MediaQuest' 'Max Five' 'Comfort' 'Monte Christo Multimedia'
 'Pony Canyon' 'Riverhillsoft' 'Summitsoft' 'Milestone S.r.l' 'Playmore'
 'MLB.com' 'Kool Kizz' 'Flashpoint Games' '49Games' 'Legacy Interactive'
 'Alawar Entertainment' 'CyberFront' 'Cloud Imperium Games Corporation'
 'Societa' 'Virtual Play Games' 'Interchannel' 'Sonnet' 'Experience Inc.'
 'Zenrin' 'Iceberg Interactive' 'Ivolgamus' '2D Boy' 'MC2 Entertainment'
 'Kando Games' 'Just Flight' 'Office Create' 'Mamba Games' 'Fields'
 'Princess Soft' 'Maximum Family Games' 'Berkeley' 'Fuji'
 'Dusenberry Martin Racing' 'imageepoch Inc.' 'Big Fish Games'
 'Her Interactive' 'Kamui' 'ASK' 'TopWare Interactive' 'Headup Games'
 'KSS' 'Cygames' 'KID' 'Quinrose' 'Sunflowers' 'dramatic create' 'TGL'
 'Encore' 'Extreme Entertainment Group' 'Intergrow' 'G.Rev' 'Sweets'
 'Kokopeli Digital Studios' 'Number None' 'Nexon' 'id Software'
 'BushiRoad' 'Tryfirst' 'Strategy First' '7G//AMES' 'GN Software' "Yuke's"
 'Easy Interactive' 'Licensed 4U' 'FuRyu Corporation'
 'Lexicon Entertainment' 'Paon Corporation' 'Kids Station' 'GOA'
 'Graphsim Entertainment' 'King Records' 'Introversion Software'
 'Minato Station' 'Devolver Digital' 'Blue Byte' 'Gaga'
 'Yamasa Entertainment' 'Plenty' 'Views' 'fonfun' 'NetRevo'
 'Codemasters Online' 'Quintet' 'Phoenix Games' 'Dorart' 'Marvelous Games'
 'Focus Multimedia' 'Imageworks' 'Karin Entertainment' 'Aerosoft'
 'Technos Japan Corporation' 'Gakken' 'Mirai Shounen' 'Datam Polystar'
 'Saurus' 'HuneX' 'Revolution (Japan)' 'Giza10' 'Visco' 'Alvion' 'Mycom'
 'Giga' 'Warashi' 'System Soft' 'Sold Out' 'Lighthouse Interactive'
 'Masque Publishing' 'RED Entertainment' 'Michaelsoft'
 'Media Entertainment' 'New World Computing' 'Genterprise'
 'Interworks Unlimited, Inc.' 'Boost On' 'Stainless Games'
 'EON Digital Entertainment' 'Epic Games' 'Naxat Soft'
 'Ascaron Entertainment' 'Piacci' 'Nitroplus' 'Paradox Development'
 'Otomate' 'Ongakukan' 'Commseed' 'Inti Creates' 'Takuyo'
 'Interchannel-Holon' 'Rain Games' 'UIG Entertainment']
 ****************************************************************************************************

In [142]:
df

,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16322,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16323,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16324,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16325,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16326,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

### Check Numerical Data in details

In [143]:
df.year

0        2006.0
1        1985.0
2        2008.0
3        2009.0
4        1996.0
          ...
16322    2002.0
16323    2003.0
16324    2008.0
16325    2010.0
16326    2003.0
Name: year, Length: 16327, dtype: float64

In [144]:
df['year'] = df['year'].astype(int)
df

,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16322,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16323,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16324,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16325,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16326,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

# Data Analysis

### Q1:What are the Total Number of Games per Genre?

In [145]:
genre_games = df.groupby('genre')['name'].count().sort_values(ascending=False).reset_index()

genre_games

           genre  name
0         Action  3253
1         Sports  2304
2           Misc  1710
3   Role-Playing  1471
4        Shooter  1282
5      Adventure  1276
6         Racing  1226
7       Platform   876
8     Simulation   851
9       Fighting   836
10      Strategy   671
11        Puzzle   571

In [146]:
px.bar(genre_games, x='genre', y='name',
       title='Total Number of Games per Genre',
       labels={'Name': 'Number of Games'})

### Q2:What are the Total Number of Games per Platform?

In [147]:
platform_games = df.groupby('platform')['name'].count().sort_values(ascending=False).reset_index()

platform_games

   platform  name
0        DS  2133
1       PS2  2127
2       PS3  1304
3       Wii  1290
4      X360  1235
5       PSP  1197
6        PS  1189
7        PC   943
8       GBA   811
9        XB   803
10       GC   542
11      3DS   500
12      PSV   412
13      PS4   336
14      N64   316
15     SNES   239
16     XOne   213
17      SAT   173
18     WiiU   143
19     2600   116
20      NES    98
21       GB    97
22       DC    52
23      GEN    27
24       NG    12
25       WS     6
26      SCD     6
27      3DO     3
28     TG16     2
29     PCFX     1
30       GG     1

In [148]:
px.bar(platform_games, x='platform', y='name',
       title='Total Number of Games per Platform',
       labels={'Name': 'Number of Games'})

### Q3:What are the Total Number of Games per Publisher (Top 20 Only)?

In [149]:
publisher_games = df.groupby('publisher')['name'].count().sort_values(ascending=False).head(20).reset_index()
publisher_games

                                 publisher  name
0                          Electronic Arts  1339
1                               Activision   966
2                       Namco Bandai Games   928
3                                  Ubisoft   918
4             Konami Digital Entertainment   823
5                                      THQ   712
6                                 Nintendo   696
7              Sony Computer Entertainment   682
8                                     Sega   632
9                     Take-Two Interactive   412
10                                  Capcom   376
11                                   Atari   347
12                              Tecmo Koei   338
13                             Square Enix   231
14  Warner Bros. Interactive Entertainment   217
15              Disney Interactive Studios   214
16                       Eidos Interactive   196
17                            Midway Games   196
18                               505 Games   192
19                  Microsoft Game Studios   189

In [150]:
px.bar(publisher_games, x='publisher', y='name',
       title='Top 20 Publishers by Number of Games Released',
       labels={'Name': 'Number of Games'})

### Q4:What are the Average Global Sales per Year?

In [151]:
avg_sales_year = df.groupby('year')['global_sales'].mean().reset_index()

avg_sales_year

    year  global_sales
0   1980      1.264444
1   1981      0.777609
2   1982      0.801667
3   1983      0.987647
4   1984      3.597143
5   1985      3.852857
6   1986      1.765238
7   1987      1.358750
8   1988      3.148000
9   1989      4.320588
10  1990      3.086875
11  1991      0.786098
12  1992      1.771163
13  1993      0.766333
14  1994      0.654298
15  1995      0.402329
16  1996      0.757224
17  1997      0.695433
18  1998      0.676702
19  1999      0.743402
20  2000      0.577536
21  2001      0.687697
22  2002      0.477105
23  2003      0.461742
24  2004      0.549554
25  2005      0.488778
26  2006      0.516905
27  2007      0.508428
28  2008      0.475420
29  2009      0.466317
30  2010      0.476926
31  2011      0.453020
32  2012      0.553333
33  2013      0.674194
34  2014      0.579124
35  2015      0.430684
36  2016      0.206192
37  2017      0.016667
38  2020      0.290000

In [152]:
px.line(avg_sales_year, x='year', y='global_sales', title='Average Global Sales Over Years',
        labels={'global_sales': 'Avg Global Sales'})

### Q5:What are the Average Global Sales per Genre?

In [153]:
avg_sales_genre = df.groupby('genre')['global_sales'].mean().sort_values(ascending=False).reset_index()

avg_sales_genre

           genre  global_sales
0       Platform      0.946518
1        Shooter      0.800468
2   Role-Playing      0.628035
3         Racing      0.592798
4         Sports      0.568247
5       Fighting      0.531160
6         Action      0.529628
7           Misc      0.466444
8     Simulation      0.458472
9         Puzzle      0.424203
10      Strategy      0.258465
11     Adventure      0.184013

In [154]:
px.bar(avg_sales_genre, x='genre', y='global_sales',
       title='Average Global Sales per Genre',
       labels={'global_sales': 'Avg Global Sales'})

### Q6:What are the Average Global Sales per Platform?

In [155]:
avg_sales_platform = df.groupby('platform')['global_sales'].mean().sort_values(ascending=False).reset_index()

avg_sales_platform

   platform  global_sales
0        GB      2.622887
1       NES      2.561939
2       GEN      1.050370
3      SNES      0.837029
4       PS4      0.827679
5      X360      0.785109
6      2600      0.746293
7       PS3      0.728029
8       Wii      0.705279
9       N64      0.690538
10     XOne      0.662254
11       PS      0.611766
12      PS2      0.579906
13     WiiU      0.572448
14      3DS      0.492560
15      GBA      0.386634
16       DS      0.383947
17       GC      0.363727
18       XB      0.313935
19      SCD      0.311667
20       DC      0.307115
21       PC      0.270467
22      PSP      0.243701
23       WS      0.236667
24      SAT      0.194162
25      PSV      0.149587
26       NG      0.120000
27     TG16      0.080000
28       GG      0.040000
29      3DO      0.033333
30     PCFX      0.030000

In [156]:
px.bar(avg_sales_platform, x='platform', y='global_sales',
       title='Average Global Sales by Platform',
       labels={'global_sales': 'Avg Global Sales'})

### Q7:What are the Average Global Sales per Publisher (Top 20)?

In [157]:
avg_sales_publisher = df.groupby('publisher')['global_sales'].mean().sort_values(ascending=False).head(20).reset_index()
avg_sales_publisher

                             publisher  global_sales
0                               Palcom      4.170000
1                              Red Orb      2.620000
2                             Nintendo      2.563836
3                  Arena Entertainment      2.360000
4                          UEP Systems      2.250000
5                            RedOctane      2.170000
6                                Valve      1.740000
7                          Hello Games      1.600000
8   Sony Computer Entertainment Europe      1.592667
9                     Westwood Studios      1.550000
10              Microsoft Game Studios      1.300476
11                              Imagic      1.205000
12                   Black Label Games      1.200000
13                  Bethesda Softworks      1.181594
14                               Maxis      1.130000
15                    Enix Corporation      1.124667
16                          SquareSoft      1.108654
17                      Valve Software      1.076667
18                Take-Two Interactive      0.969175
19                           LucasArts      0.954494

In [158]:
px.bar(avg_sales_publisher, x='publisher', y='global_sales',
       title='Top 20 Publishers by Avg Global Sales per Game',
       labels={'global_sales': 'Avg Global Sales'})

### Q8:What are the Top 10 Best-Selling Games Globally?

In [159]:
top_10_games = df[['name', 'global_sales']].sort_values(by='global_sales', ascending=False).head(10)
top_10_games

                        name  global_sales
0                 Wii Sports         82.74
1          Super Mario Bros.         40.24
2             Mario Kart Wii         35.82
3          Wii Sports Resort         33.00
4   Pokemon Red/Pokemon Blue         31.37
5                     Tetris         30.26
6      New Super Mario Bros.         30.01
7                   Wii Play         29.02
8  New Super Mario Bros. Wii         28.62
9                  Duck Hunt         28.31

In [160]:
px.bar(top_10_games, x='name', y='global_sales',
       title='Top 10 Best-Selling Games Globally',
       labels={'global_sales': 'Global Sales'})

### Q9:What are the Total Sales per Region?

In [161]:
region_sales = df[['na_sales', 'eu_sales', 'jp_sales', 'other_sales']].sum().reset_index()
region_sales.columns = ['Region', 'Sales']

region_sales

        Region    Sales
0     na_sales  4333.43
1     eu_sales  2409.12
2     jp_sales  1284.30
3  other_sales   789.01

In [162]:
px.pie(region_sales, names='Region', values='Sales', title='Sales Distribution by Region',)

### Q10:What are the Total Global Sales per Year?

In [163]:
total_sales_year = df.groupby('year')['global_sales'].sum().reset_index()

total_sales_year

    year  global_sales
0   1980         11.38
1   1981         35.77
2   1982         28.86
3   1983         16.79
4   1984         50.36
5   1985         53.94
6   1986         37.07
7   1987         21.74
8   1988         47.22
9   1989         73.45
10  1990         49.39
11  1991         32.23
12  1992         76.16
13  1993         45.98
14  1994         79.17
15  1995         88.11
16  1996        199.15
17  1997        200.98
18  1998        256.47
19  1999        251.27
20  2000        201.56
21  2001        331.47
22  2002        395.52
23  2003        357.85
24  2004        419.31
25  2005        459.94
26  2006        521.04
27  2007        611.13
28  2008        678.90
29  2009        667.30
30  2010        600.45
31  2011        515.99
32  2012        363.54
33  2013        368.11
34  2014        337.05
35  2015        264.44
36  2016         70.93
37  2017          0.05
38  2020          0.29

In [164]:
px.line(total_sales_year, x='year', y='global_sales',
        title='Total Global Sales per Year',
        labels={'global_sales': 'Total Global Sales'})

### Q11: Which combination of platform and genre generates the highest total global sales?

In [165]:
grouped = df.groupby(['platform', 'genre'])['global_sales'].sum().reset_index()
grouped

    platform         genre  global_sales
0       2600        Action         26.39
1       2600     Adventure          0.40
2       2600      Fighting          0.77
3       2600          Misc          3.58
4       2600      Platform         13.27
..       ...           ...           ...
288     XOne  Role-Playing          9.48
289     XOne       Shooter         51.61
290     XOne    Simulation          0.54
291     XOne        Sports         23.97
292     XOne      Strategy          0.38

[293 rows x 3 columns]

In [166]:

fig = px.bar(grouped.sort_values(by='global_sales', ascending=False).head(40),
             x='platform',
             y='global_sales',
             color='genre',
             title='Top Platform-Genre Combinations by Global Sales')
fig

### Save cleaned dataframe for later use in streamlit python file

In [167]:
df.to_csv('cleaned_VGsales.csv', index=False)

# Streamlit

In [168]:
%%writefile VGsales.py

# Import necessary Libraries
import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

# Load the cleaned dataset
df = pd.read_csv('cleaned_VGsales.csv')

st.title(" Video Game Sales Dashboard")

# Sidebar filters
st.sidebar.header("Filter Data")
Game = st.sidebar.multiselect("Select Game(s)", df['name'].unique())
platforms = st.sidebar.multiselect("Select Platform(s)", df['platform'].unique())
genres = st.sidebar.multiselect("Select Genre(s)", df['genre'].unique())
publishers = st.sidebar.multiselect("Select Publisher(s)", df['publisher'].unique())
year_range = st.sidebar.slider("Select Year Range", 
                               int(df['year'].min()), 
                               int(df['year'].max()), 
                               (int(df['year'].min()), int(df['year'].max())))

# Apply filters
filtered_df = df.copy()

if Game:
    filtered_df = filtered_df[filtered_df['name'].isin(Game)]

if platforms:
    filtered_df = filtered_df[filtered_df['platform'].isin(platforms)]

if genres:
    filtered_df = filtered_df[filtered_df['genre'].isin(genres)]

if publishers:
    filtered_df = filtered_df[filtered_df['publisher'].isin(publishers)]

filtered_df = filtered_df[(filtered_df['year'] >= year_range[0]) & (filtered_df['year'] <= year_range[1])]

# Visualizations
st.subheader("Data Table")
st.dataframe(filtered_df.head(50))

st.subheader("Top 10 Best-Selling Games")
top_games = filtered_df.sort_values(by="global_sales", ascending=False).head(10)
fig = px.bar(top_games, x="name", y="global_sales", title="Top 10 Games by Global Sales", labels={'global_sales': 'Global Sales (in millions)'})
st.plotly_chart(fig)

st.subheader("Sales Distribution by Region")
region_cols = ['na_sales', 'eu_sales', 'jp_sales', 'other_sales']
region_sums = filtered_df[region_cols].sum().reset_index()
region_sums.columns = ['Region', 'Sales']
fig2 = px.pie(region_sums, names='Region', values='Sales', title="Regional Sales Distribution")
st.plotly_chart(fig2)

st.subheader("Game Sales Over the Years")
sales_by_year = filtered_df.groupby('year')['global_sales'].sum().reset_index()
fig3 = px.line(sales_by_year, x='year', y='global_sales', title="Total Global Sales by Year", labels={'global_sales': 'Global Sales'})
st.plotly_chart(fig3)

st.subheader("Relationship Between Platform, Genre, and Global Sales")
grouped = filtered_df.groupby(['platform', 'genre'])['global_sales'].sum().reset_index()
fig4 = px.bar(grouped.sort_values(by='global_sales', ascending=False).head(40),
             x='platform',
             y='global_sales',
             color='genre',
             title='Top Platform-Genre Combinations by Global Sales',
             labels={'global_sales': 'Global Sales (in millions)'})
st.plotly_chart(fig4)

Overwriting VGsales.py

In [45]:
! streamlit run VGsales.py

^C

# Data Preprocessing

### 1) Split Data into input features and Target Variable

In [169]:
x = df.drop(columns=['global_sales', 'name'])
y = df['global_sales']

### 2) Split Data into Train & Test

In [170]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 42)

### 3) Handling Numerical Columns

In [171]:
scaling_cols = x_train.select_dtypes(include= 'number').columns
scaling_cols

Index(['year', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales'], dtype='object')

In [172]:
from sklearn.preprocessing import RobustScaler

rc = RobustScaler()

x_train[scaling_cols] = rc.fit_transform(x_train[scaling_cols])
x_test[scaling_cols] = rc.transform(x_test[scaling_cols])

### 4) Handling Categorical Columns

In [173]:
x_train.select_dtypes(include= 'object')

      platform     genre                    publisher
14237       PC  Strategy                     Pinnacle
1621       NES    Puzzle           Namco Bandai Games
14880       PC    Racing                        Atari
12736     X360    Sports              Electronic Arts
7608       PS2    Sports  Sony Computer Entertainment
...        ...       ...                          ...
13418       PC  Strategy              Electronic Arts
5390        DS    Puzzle                     Nintendo
860       X360   Shooter                      Ubisoft
15795     X360  Platform       Microsoft Game Studios
7270       3DS    Action      Marvelous Entertainment

[13061 rows x 3 columns]

In [174]:
n1_cols = x_train.select_dtypes(include= 'object').drop('publisher', axis = 1).columns
n1_cols

Index(['platform', 'genre'], dtype='object')

In [175]:
n2_col = ['publisher']
n2_col

['publisher']

In [176]:
for col in n1_cols:
    print(col)
    print(df[col].nunique())

platform
31
genre
12

In [177]:
for col in n2_col:
    print(col)
    print(df[col].nunique())

publisher
576

In [178]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output= False, drop= 'first')

ohe_train_arr = ohe.fit_transform(x_train[n1_cols])
ohe_test_arr = ohe.transform(x_test[n1_cols])

In [179]:
ohe_train_df = pd.DataFrame(ohe_train_arr, columns= ohe.get_feature_names_out())
ohe_test_df = pd.DataFrame(ohe_test_arr, columns= ohe.get_feature_names_out())
ohe_train_df

,platform_3DO,platform_3DS,platform_DC,platform_DS,platform_GB,platform_GBA,platform_GC,platform_GEN,platform_GG,platform_N64,...,genre_Fighting,genre_Misc,genre_Platform,genre_Puzzle,genre_Racing,genre_Role-Playing,genre_Shooter,genre_Simulation,genre_Sports,genre_Strategy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13057,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13058,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13059,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13060,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [180]:
from category_encoders import BinaryEncoder

bin_enc = BinaryEncoder()
bin_train_df = bin_enc.fit_transform(x_train['publisher'])
bin_test_df = bin_enc.transform(x_test['publisher'])

In [181]:
bin_train_df.reset_index(drop=True, inplace=True)
bin_test_df.reset_index(drop=True, inplace=True)

In [182]:
x_train

,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales
14237,PC,0.142857,Strategy,Pinnacle,-0.333333,0.000000,0.00,0.00
1621,NES,-3.285714,Puzzle,Namco Bandai Games,0.791667,0.545455,21.25,0.25
14880,PC,0.000000,Racing,Atari,-0.333333,0.000000,0.00,-0.25
12736,X360,0.000000,Sports,Electronic Arts,-0.166667,-0.090909,0.00,-0.25
7608,PS2,-0.857143,Sports,Sony Computer Entertainment,0.083333,0.454545,0.00,0.25
...,...,...,...,...,...,...,...,...
13418,PC,-0.857143,Strategy,Electronic Arts,-0.333333,0.181818,0.00,0.00
5390,DS,0.000000,Puzzle,Nintendo,0.250000,-0.090909,4.00,0.00
860,X360,-0.142857,Shooter,Ubisoft,4.208333,5.727273,0.50,4.75
15795,X360,0.142857,Platform,Microsoft Game Studios,-0.333333,-0.090909,0.00,-0.25
7270,3DS,1.000000,Action,Marvelous Entertainment,0.041667,0.090909,2.00,0.00

In [183]:
x_train.reset_index(inplace= True, drop= True)
x_test.reset_index(inplace= True, drop= True)

y_train.reset_index(inplace= True, drop= True)
y_test.reset_index(inplace= True, drop= True)

In [184]:
x_train = pd.concat([x_train, ohe_train_df], axis= 1).drop(n1_cols, axis= 1)

x_test = pd.concat([x_test, ohe_test_df], axis= 1).drop(n1_cols, axis= 1)

x_train = pd.concat([x_train.drop('publisher', axis=1), bin_train_df], axis=1)
x_test = pd.concat([x_test.drop('publisher', axis=1), bin_test_df], axis=1)

In [185]:
x_train.head()

,year,na_sales,eu_sales,jp_sales,other_sales,platform_3DO,platform_3DS,platform_DC,platform_DS,platform_GB,...,publisher_0,publisher_1,publisher_2,publisher_3,publisher_4,publisher_5,publisher_6,publisher_7,publisher_8,publisher_9
0,0.142857,-0.333333,0.000000,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1,-3.285714,0.791667,0.545455,21.25,0.25,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,0
2,0.000000,-0.333333,0.000000,0.00,-0.25,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,1
3,0.000000,-0.166667,-0.090909,0.00,-0.25,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
4,-0.857143,0.083333,0.454545,0.00,0.25,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,1